version: 2
jobs:
  build:
    machine:
      node:
        version: v11.1.0

    steps:
      - checkout
      - run:
          name: hoge
          command: echo fuga
      - run:
          name: fuga
          command: |
            npm install
            npm run danger
