version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: install yarn
          command: sudo apt-get update && sudo apt-get install yarn
      - run:
          name: Danger
          command: yarn danger ci
