version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: install yarn
          command: apt-get update && apt-get install yarn
      - run:
          name: Danger
          command: yarn danger ci
